# -*- coding: utf-8 -*-
"""Big Data_Kelompok 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9EMNDIQGwVmMd_0uPPfcwdDMZtR6FV3

# BAGIAN 1: Data Storage & Data Understanding
---

# **Laporan Data Storage & Data Understanding**

**Topik:** Analisis Temporal Tren Review dan Pola Perilaku Konsumen di Tokopedia (2015–2025)

**Tujuan Notebook ini:**
1. Menyimpan dan memuat raw dataset dari Google Drive.
2. Memahami struktur awal data (baris, kolom, tipe data).
3. Melakukan Data Cleaning (menghapus duplikasi, menangani missing values).
4. Melakukan Feature Engineering (mengekstrak fitur waktu dari `review_date`).
"""

# IMPORT LIBRARY DAN UPLOAD FILE MANUAL
import pandas as pd
from google.colab import files

# Upload file CSV dari komputer kamu
# Setelah run cell ini, klik tombol "Choose Files" dan pilih file tokopedia_product_reviews_2025.csv
uploaded = files.upload()

# Membaca dataset dari file yang diupload
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print(f"File '{file_name}' berhasil dimuat!")
print(f"Jumlah baris: {df.shape[0]:,} | Jumlah kolom: {df.shape[1]}")

"""## **1. Pengecekan Kondisi Data Awal**
Melihat ukuran data, tipe data tiap kolom, dan mengecek baris duplikat.
"""

# Melihat 5 baris teratas
display(df.head())

# Mengecek informasi data (jumlah baris, kolom, dan tipe data)
print("\n--- INFO DATA ---")
df.info()

# Mengecek jumlah duplikasi
jumlah_duplikat = df.duplicated().sum()
print(f"\nJumlah baris duplikat: {jumlah_duplikat}")

# Menghapus duplikasi jika ada
if jumlah_duplikat > 0:
    df = df.drop_duplicates()
    print("Baris duplikat berhasil dihapus.")

"""## **2. Penanganan Missing Values**
Terdapat missing values pada kolom `product_variant`. Kita akan mengisinya dengan label "Tanpa Varian".
"""

# Cek total missing values per kolom
print("--- MISSING VALUES SEBELUM CLEANING ---")
print(df.isnull().sum())

# Mengisi missing values di kolom product_variant
df['product_variant'] = df['product_variant'].fillna('Tanpa Varian')

# Memastikan tidak ada lagi missing values di product_variant
print("\n--- MISSING VALUES SETELAH CLEANING ---")
print(df.isnull().sum())

"""## **3. Parsing Tanggal (Ekstraksi Temporal)**
Mengubah `review_date` menjadi tipe Datetime, lalu membuat kolom `year`, `month`, `quarter`, dan `day_of_week`.
"""

# Mengubah ke format datetime
# Note: errors='coerce' akan mengubah data yang formatnya salah menjadi NaT (Not a Time)
df['review_date'] = pd.to_datetime(df['review_date'], errors='coerce')

# Mengekstrak kolom temporal
df['year'] = df['review_date'].dt.year
df['month'] = df['review_date'].dt.month
df['quarter'] = df['review_date'].dt.to_period('Q').astype(str) # Contoh output: 2023Q1
df['day_of_week'] = df['review_date'].dt.day_name() # Contoh output: Monday, Tuesday

# Mengecek apakah kolom berhasil terbuat
display(df[['review_date', 'year', 'month', 'quarter', 'day_of_week']].head())

"""## **4. Validasi Kolom Sentimen**
Memastikan isi dari kolom `sentiment_label` hanya 'positive', 'neutral', atau 'negative'.
"""

# Melihat nilai unik di kolom sentiment_label
print("--- DISTRIBUSI SENTIMEN ---")
print(df['sentiment_label'].value_counts(dropna=False))

# Opsional: Jika misal ada huruf besar/kecil yang tidak seragam, kita rapikan (lowercase)
df['sentiment_label'] = df['sentiment_label'].astype(str).str.lower().str.strip()

# Validasi ulang
print("\n--- DISTRIBUSI SENTIMEN SETELAH DIRAPIKAN ---")
print(df['sentiment_label'].value_counts())

"""## **5. Ekspor Data Bersih**
Menyimpan data yang sudah rapi ke dalam folder Google Drive
"""

# Menyimpan data bersih ke file lokal lalu download ke komputer
save_name = 'clean_tokopedia_reviews.csv'
df.to_csv(save_name, index=False)

# Otomatis download file ke komputer kamu
files.download(save_name)

print(f"✅ Data bersih berhasil disimpan dan didownload sebagai '{save_name}'")
print(f"   Jumlah baris: {df.shape[0]:,} | Jumlah kolom: {df.shape[1]}")

import matplotlib.pyplot as plt
import seaborn as sns

"""## **6. Statistik Ringkasan Numerik**"""

print("=" * 60)
print("EDA 1: STATISTIK DESKRIPTIF KOLOM NUMERIK")
print("=" * 60)

# Ringkasan statistik (mean, median, std, min, max, quartile)
kolom_numerik = ['rating', 'product_price', 'sold_count']
print(df[kolom_numerik].describe().round(2))

print("\n--- MEDIAN ---")
for col in kolom_numerik:
    print(f"  Median {col}: {df[col].median()}")

print("\n--- MODUS ---")
for col in kolom_numerik:
    print(f"  Modus {col}: {df[col].mode()[0]}")

"""## **7. Distribusi Rating**"""

import matplotlib.pyplot as plt
import seaborn as sns

print("=" * 60)
print("EDA 2: DISTRIBUSI RATING")
print("=" * 60)

print(df['rating'].value_counts().sort_index())
print(f"\nPersentase:")
print((df['rating'].value_counts(normalize=True).sort_index() * 100).round(2))

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Bar chart frekuensi
df['rating'].value_counts().sort_index().plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title('Frekuensi Rating')
axes[0].set_xlabel('Rating (Bintang)')
axes[0].set_ylabel('Jumlah Review')
axes[0].tick_params(axis='x', rotation=0)

# Pie chart proporsi
df['rating'].value_counts().sort_index().plot(kind='pie', ax=axes[1], autopct='%1.1f%%',
                                               colors=['#d73027','#fc8d59','#fee090','#91bfdb','#4575b4'])
axes[1].set_title('Proporsi Rating')
axes[1].set_ylabel('')

plt.suptitle('EDA 2: Distribusi Rating Konsumen', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""## **8. Distribusi Sentimen**"""

print("=" * 60)
print("EDA 3: DISTRIBUSI SENTIMEN LABEL")
print("=" * 60)

print(df['sentiment_label'].value_counts())
print(f"\nPersentase:")
print((df['sentiment_label'].value_counts(normalize=True) * 100).round(2))

fig, ax = plt.subplots(figsize=(7, 4))
warna_sentimen = {'positive': '#2ecc71', 'neutral': '#95a5a6', 'negative': '#e74c3c'}
sentimen_counts = df['sentiment_label'].value_counts()
bars = ax.bar(sentimen_counts.index, sentimen_counts.values,
              color=[warna_sentimen.get(k, 'gray') for k in sentimen_counts.index], edgecolor='black')
for bar, val in zip(bars, sentimen_counts.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50, f'{val:,}', ha='center', fontsize=10)
ax.set_title('EDA 3: Distribusi Sentimen Label', fontsize=13, fontweight='bold')
ax.set_xlabel('Sentimen')
ax.set_ylabel('Jumlah Review')
plt.tight_layout()
plt.show()

"""## **9. Distribusi Harga & Jumlah Penjualan**"""

print("=" * 60)
print("EDA 4: DISTRIBUSI HARGA & JUMLAH PENJUALAN")
print("=" * 60)

fig, axes = plt.subplots(2, 2, figsize=(14, 8))

# Histogram harga (filter outlier ekstrem)
df_harga = df[df['product_price'] < df['product_price'].quantile(0.95)]
axes[0][0].hist(df_harga['product_price'], bins=40, color='steelblue', edgecolor='black')
axes[0][0].set_title('Distribusi Harga Produk (tanpa top 5% outlier)')
axes[0][0].set_xlabel('Harga (Rp)')
axes[0][0].set_ylabel('Frekuensi')

# Boxplot harga
axes[0][1].boxplot(df_harga['product_price'], vert=False)
axes[0][1].set_title('Boxplot Harga Produk')
axes[0][1].set_xlabel('Harga (Rp)')

# Histogram sold_count
df_sold = df[df['sold_count'] < df['sold_count'].quantile(0.95)]
axes[1][0].hist(df_sold['sold_count'], bins=40, color='orange', edgecolor='black')
axes[1][0].set_title('Distribusi Jumlah Penjualan (tanpa top 5% outlier)')
axes[1][0].set_xlabel('Sold Count')
axes[1][0].set_ylabel('Frekuensi')

# Boxplot sold_count
axes[1][1].boxplot(df_sold['sold_count'], vert=False)
axes[1][1].set_title('Boxplot Jumlah Penjualan')
axes[1][1].set_xlabel('Sold Count')

plt.suptitle('EDA 4: Distribusi Harga & Penjualan', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""## **10. Tren Review Per Tahun & Per Bulan**"""

print("=" * 60)
print("EDA 5: TREN TEMPORAL REVIEW")
print("=" * 60)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Review per tahun
review_per_tahun = df.groupby('year').size()
review_per_tahun.plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title('Jumlah Review per Tahun')
axes[0].set_xlabel('Tahun')
axes[0].set_ylabel('Jumlah Review')
axes[0].tick_params(axis='x', rotation=45)

# Review per bulan (rata-rata semua tahun)
review_per_bulan = df.groupby('month').size()
bulan_label = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
axes[1].bar(range(1, 13), review_per_bulan.values, color='teal', edgecolor='black')
axes[1].set_xticks(range(1, 13))
axes[1].set_xticklabels(bulan_label, rotation=45)
axes[1].set_title('Distribusi Review per Bulan')
axes[1].set_xlabel('Bulan')
axes[1].set_ylabel('Jumlah Review')

plt.suptitle('EDA 5: Pola Temporal Review', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""## **11. Rata-rata Rating per Sentimen & per Tahun**"""

print("=" * 60)
print("EDA 6: KARAKTERISTIK RATING BERDASARKAN SENTIMEN & TAHUN")
print("=" * 60)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Rata-rata rating per sentimen
avg_rating_sentimen = df.groupby('sentiment_label')['rating'].mean().sort_values()
warna = [warna_sentimen.get(k, 'gray') for k in avg_rating_sentimen.index]
axes[0].bar(avg_rating_sentimen.index, avg_rating_sentimen.values, color=warna, edgecolor='black')
axes[0].set_title('Rata-rata Rating per Sentimen')
axes[0].set_xlabel('Sentimen')
axes[0].set_ylabel('Rata-rata Rating')
axes[0].set_ylim(0, 5.5)
for i, v in enumerate(avg_rating_sentimen.values):
    axes[0].text(i, v + 0.05, f'{v:.2f}', ha='center')

# Rata-rata rating per tahun
avg_rating_tahun = df.groupby('year')['rating'].mean()
axes[1].plot(avg_rating_tahun.index, avg_rating_tahun.values, marker='o', color='steelblue')
axes[1].set_title('Rata-rata Rating per Tahun')
axes[1].set_xlabel('Tahun')
axes[1].set_ylabel('Rata-rata Rating')
axes[1].set_ylim(4, 5.1)
axes[1].grid(True, linestyle='--', alpha=0.5)

plt.suptitle('EDA 6: Karakteristik Rating', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Tabel ringkasan
print("\n--- Rata-rata & Median Rating per Sentimen ---")
print(df.groupby('sentiment_label')['rating'].agg(['mean', 'median', 'count']).round(2))

"""# 📋 Kesimpulan EDA

## Ringkasan Dataset
- **Total data bersih:** 65.543 review produk Tokopedia (2015–2025)
- **Jumlah kolom:** 17 kolom (setelah feature engineering)
- **Tidak ada missing values** tersisa setelah cleaning

---

## Temuan Utama

### 1. Rating Sangat Didominasi Bintang 5
- **93.87%** review memberikan rating 5 bintang (61.525 dari 65.543 review)
- Rating 1–3 hanya menyumbang **2.43%** total review
- **Mean rating: 4.89 | Median & Modus: 5.0** → distribusi sangat *left-skewed*
- Implikasi: data rating tidak terdistribusi normal, perlu diperhatikan saat modeling

### 2. Sentimen Sangat Tidak Seimbang
- **Positive: 97.56%** (63.943 review), Neutral: 1.22% (802), Negative: 1.22% (798)
- Ketidakseimbangan kelas ini sangat ekstrem
- Rata-rata rating per sentimen: Negative=1.31, Neutral=3.00, Positive=4.96 → konsisten dan masuk akal

### 3. Harga & Penjualan Memiliki Distribusi Sangat Skewed
- **Median harga: Rp 80.000 | Mean: Rp 542.129** → selisih besar menandakan banyak outlier harga tinggi
- **Median sold_count: 500 | Mean: 1.954** → sebagian kecil produk mendominasi penjualan
- **Modus harga: Rp 45.000 | Modus sold_count: 100** → mayoritas produk adalah produk murah dengan penjualan kecil
- Max harga: Rp 99.999.000 dan max sold_count: 1.000.000 mengonfirmasi adanya outlier ekstrem

### 4. Tren Review Terus Meningkat Signifikan
- Volume review **hampir nol di 2015–2017**, lalu mulai tumbuh pesat ab 2019
- Puncak tertinggi di **2024 (~15.500 review/tahun)** diikuti 2025 (~15.000)
- Lonjakan besar terjadi saat **pandemi 2020–2021** → kemungkinan besar seiring pertumbuhan e-commerce
- Distribusi per bulan relatif merata di **3.000–7.000 review/bulan**, tidak ada bulan yang sangat dominan

### 5. Tren Rating Stabil Setelah 2018
- Rating sempat turun di **2016 (4.56)** lalu naik kembali dan stabil di kisaran **4.83–4.96** dari 2019–2025
- Tidak ada tren penurunan kualitas meskipun volume review meningkat drastis

# BAGIAN 2: Data Analytics & Modelling
---

# **Import Dataset**
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install prophet imbalanced-learn pyspark --quiet
print("✅ Semua library berhasil diinstall!")

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Orang4_Tokopedia_Analytics") \
    .config("spark.driver.memory", "2g") \
    .getOrCreate()

spark.sparkContext.setLogLevel("ERROR")
print(f"✅ SparkSession aktif! Spark Version: {spark.version}")

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

DATA_PATH = '/content/drive/MyDrive/Project_BigData_Kel2 (1)/clean_tokopedia_reviews.csv'
OUTPUT_PATH = '/content/drive/MyDrive/Project_BigData_Kel2 (1)/'

df = pd.read_csv(DATA_PATH)

print("✅ Dataset berhasil dimuat!")
print(f"   Jumlah baris  : {df.shape[0]:,}")
print(f"   Jumlah kolom  : {df.shape[1]}")
print(f"\nDistribusi Rating:\n{df['rating'].value_counts().sort_index()}")
print(f"\nDistribusi Sentimen:\n{df['sentiment_label'].value_counts()}")

!pip install prophet imbalanced-learn pyspark --quiet
print("✅ Semua library berhasil diinstall!")

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Orang4_Tokopedia_Analytics") \
    .config("spark.driver.memory", "2g") \
    .getOrCreate()

spark.sparkContext.setLogLevel("ERROR")
print(f"✅ SparkSession aktif!")
print(f"   Spark Version: {spark.version}")

from scipy import stats
from scipy.stats import mannwhitneyu
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, r2_score, mean_squared_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from imblearn.over_sampling import SMOTE
from prophet import Prophet
import matplotlib.pyplot as plt
import seaborn as sns

print("✅ Semua library berhasil diimport!")
print("🚀 Siap mulai analisis!")

"""## **Analisis #1 — Spearman Correlation + Logistic Regression**"""

print("=" * 60)
print("ANALISIS 1: PENGARUH HARGA TERHADAP RATING")
print("=" * 60)

corr, p_value = stats.spearmanr(df['product_price'], df['rating'])

print(f"\n📊 SPEARMAN CORRELATION:")
print(f"   Koefisien Korelasi (rho) : {corr:.4f}")
print(f"   P-value                  : {p_value:.4f}")

if p_value < 0.05:
    print(f"\n✅ Korelasi SIGNIFIKAN secara statistik (p < 0.05)")
else:
    print(f"\n⚠️  Korelasi TIDAK signifikan secara statistik (p >= 0.05)")

if abs(corr) < 0.1:
    kekuatan = "sangat lemah"
elif abs(corr) < 0.3:
    kekuatan = "lemah"
elif abs(corr) < 0.5:
    kekuatan = "sedang"
else:
    kekuatan = "kuat"

print(f"   Kekuatan korelasi: {kekuatan} ({'positif' if corr > 0 else 'negatif'})")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Boxplot harga per rating (tanpa outlier ekstrem)
df_plot = df[df['product_price'] < df['product_price'].quantile(0.95)]
df_plot.boxplot(column='product_price', by='rating', ax=axes[0])
axes[0].set_title('Distribusi Harga per Rating')
axes[0].set_xlabel('Rating (Bintang)')
axes[0].set_ylabel('Harga Produk (Rp)')

# Rata-rata harga per rating
avg_price = df.groupby('rating')['product_price'].mean()
axes[1].bar(avg_price.index, avg_price.values, color='steelblue', edgecolor='black')
axes[1].set_title('Rata-rata Harga per Rating')
axes[1].set_xlabel('Rating (Bintang)')
axes[1].set_ylabel('Rata-rata Harga (Rp)')
for i, v in enumerate(avg_price.values):
    axes[1].text(i + 1, v + 50000, f'Rp{v:,.0f}', ha='center', fontsize=7, rotation=20)

plt.suptitle('Analisis 1: Pengaruh Harga terhadap Rating', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUTPUT_PATH}orang4_analisis1_harga_vs_rating.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Grafik disimpan!")

import os
OUTPUT_PATH = '/content/orang4_outputs/'
os.makedirs(OUTPUT_PATH, exist_ok=True)
print(f"✅ OUTPUT_PATH diperbarui: {OUTPUT_PATH}")

print("📊 LOGISTIC REGRESSION:")

df['rating_binary'] = (df['rating'] >= 4).astype(int)

X = df[['product_price']].values
y = df['rating_binary'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_lr = LogisticRegression(random_state=42, max_iter=1000)
model_lr.fit(X_train_scaled, y_train)
y_pred = model_lr.predict(X_test_scaled)

print(classification_report(y_test, y_pred,
      target_names=['Tidak Puas (1-3)', 'Puas (4-5)']))
print(f"🔑 Koefisien: {model_lr.coef_[0][0]:.4f}")
print("   (Mendekati 0 = harga tidak berpengaruh besar terhadap kepuasan)")

"""📊 Interpretasi Hasil Analisis #1:

Spearman Correlation → korelasi sangat lemah, artinya harga dan rating tidak berkorelasi signifikan.

Logistic Regression:
- Akurasi 97% terlihat bagus, tapi ini menipu — model hanya belajar menebak "Puas" untuk semua input karena 93.9% data memang rating 4-5
- Precision "Tidak Puas" = 0.00 → model sama sekali tidak bisa mendeteksi konsumen tidak puas
- Koefisien 1.1278 (bukan mendekati 0) tapi tetap tidak bermakna karena model gagal total pada kelas minoritas

**Kesimpulan bisnis: Harga produk bukan penentu kepuasan konsumen di Tokopedia.**

# **Analisis #2 — Mann-Whitney U Test (Harbolnas)**
"""

print("=" * 60)
print("ANALISIS 2: UJI KEPUASAN KONSUMEN SAAT HARBOLNAS (DESEMBER)")
print("=" * 60)

rating_desember = df[df['month'] == 12]['rating']
rating_bukan_desember = df[df['month'] != 12]['rating']

print(f"\n📊 STATISTIK DESKRIPTIF:")
print(f"   Desember   — n={len(rating_desember):,} | Median={rating_desember.median()} | Mean={rating_desember.mean():.3f}")
print(f"   Bukan Des. — n={len(rating_bukan_desember):,} | Median={rating_bukan_desember.median()} | Mean={rating_bukan_desember.mean():.3f}")

stat, p_val = mannwhitneyu(rating_desember, rating_bukan_desember, alternative='less')

print(f"\n📊 MANN-WHITNEY U TEST:")
print(f"   U Statistic : {stat:.2f}")
print(f"   P-value     : {p_val:.6f}")

if p_val < 0.05:
    print(f"\n✅ Kesimpulan: Ada penurunan signifikan rating di Desember (p < 0.05)")
    print(f"   → Kepuasan konsumen LEBIH RENDAH saat Harbolnas!")
else:
    print(f"\n⚠️  Kesimpulan: Tidak ada penurunan signifikan rating di Desember (p >= 0.05)")
    print(f"   → Kepuasan konsumen tidak berbeda secara statistik saat Harbolnas.")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Rata-rata rating per bulan
avg_rating_monthly = df.groupby('month')['rating'].mean()
bulan = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
colors = ['red' if m == 12 else 'steelblue' for m in range(1, 13)]
axes[0].bar(range(1, 13), avg_rating_monthly.values, color=colors, edgecolor='black')
axes[0].set_xticks(range(1, 13))
axes[0].set_xticklabels(bulan, rotation=45)
axes[0].set_title('Rata-rata Rating per Bulan\n(Merah = Desember/Harbolnas)')
axes[0].set_ylabel('Rata-rata Rating')
axes[0].set_ylim(4.5, 5.1)
axes[0].axhline(avg_rating_monthly.mean(), color='orange', linestyle='--', label='Rata-rata Keseluruhan')
axes[0].legend()

# Distribusi rating: Desember vs lainnya
rating_des_pct = rating_desember.value_counts(normalize=True).sort_index() * 100
rating_non_pct = rating_bukan_desember.value_counts(normalize=True).sort_index() * 100
x = np.arange(1, 6)
axes[1].bar(x - 0.2, rating_des_pct.values, 0.4, label='Desember', color='red', alpha=0.7)
axes[1].bar(x + 0.2, rating_non_pct.values, 0.4, label='Bukan Desember', color='steelblue', alpha=0.7)
axes[1].set_xticks(x)
axes[1].set_title('Distribusi Rating: Desember vs Bulan Lain (%)')
axes[1].set_xlabel('Rating')
axes[1].set_ylabel('Persentase (%)')
axes[1].legend()

plt.suptitle('Analisis 2: Kepuasan Konsumen Saat Harbolnas', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUTPUT_PATH}orang4_analisis2_harbolnas.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Grafik disimpan!")

"""📊 Interpretasi Hasil Analisis #2:

- p-value = 0.1159 → jauh di atas 0.05, artinya tidak ada penurunan signifikan
- Mean Desember (4.888) vs Bukan Desember (4.894) → selisihnya hanya 0.006 secara praktis tidak berarti
- Median sama persis di 5.0 untuk keduanya

**Kesimpulan bisnis: Meskipun Harbolnas identik dengan lonjakan order dan tekanan logistik, kepuasan konsumen Tokopedia tetap stabil di bulan Desember.**

Ini bisa berarti sistem Tokopedia cukup tangguh menangani peak season, atau konsumen sudah memaklumi keterlambatan pengiriman saat Harbolnas.

# **Analisis #4 — TF-IDF + SVM + SMOTE**
"""

print("=" * 60)
print("ANALISIS 4: KLASIFIKASI SENTIMEN TF-IDF + SVM + SMOTE")
print("=" * 60)

df_nlp = df[['review_text', 'sentiment_label']].dropna()
df_nlp = df_nlp[df_nlp['sentiment_label'].isin(['positive', 'neutral', 'negative'])]

print(f"\n📊 Distribusi kelas SEBELUM SMOTE:")
print(df_nlp['sentiment_label'].value_counts())
print(f"\nTotal data: {len(df_nlp):,}")

X_text = df_nlp['review_text'].astype(str)
y_sentiment = df_nlp['sentiment_label']

X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(
    X_text, y_sentiment, test_size=0.2, random_state=42, stratify=y_sentiment
)

print(f"\n✅ Data split selesai!")
print(f"   Train: {len(X_train_t):,} | Test: {len(X_test_t):,}")

print("⏳ Proses TF-IDF... (mungkin 1-2 menit)")

tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2), min_df=3)
X_train_tfidf = tfidf.fit_transform(X_train_t)
X_test_tfidf = tfidf.transform(X_test_t)

print(f"✅ TF-IDF selesai!")
print(f"   Shape train : {X_train_tfidf.shape}")
print(f"   Shape test  : {X_test_tfidf.shape}")

print("⏳ Proses SMOTE... (mungkin 2-3 menit)")

from collections import Counter
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_tfidf, y_train_t)

print(f"\n📊 Distribusi kelas SETELAH SMOTE:")
print(Counter(y_train_resampled))
print(f"\n✅ SMOTE selesai!")

print("⏳ Training SVM... (mungkin 1-2 menit)")

svm_model = LinearSVC(random_state=42, max_iter=2000)
svm_model.fit(X_train_resampled, y_train_resampled)
y_pred_svm = svm_model.predict(X_test_tfidf)

print("✅ Training selesai!")
print(f"\n📊 HASIL KLASIFIKASI SVM + SMOTE:")
print(classification_report(y_test_t, y_pred_svm,
      target_names=['negative', 'neutral', 'positive']))

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
kelas_list = ['negative', 'neutral', 'positive']
warna = ['red', 'gray', 'green']
feature_names = np.array(tfidf.get_feature_names_out())

for i, (kelas, warna_bar) in enumerate(zip(kelas_list, warna)):
    if kelas in svm_model.classes_:
        idx_kelas = list(svm_model.classes_).index(kelas)
        top_indices = np.argsort(svm_model.coef_[idx_kelas])[-15:]
        top_words = feature_names[top_indices]
        top_scores = svm_model.coef_[idx_kelas][top_indices]
        axes[i].barh(top_words, top_scores, color=warna_bar, alpha=0.7)
        axes[i].set_title(f'Top 15 Kata Penentu\nSentimen "{kelas.capitalize()}"')
        axes[i].set_xlabel('Koefisien SVM')

plt.suptitle('Analisis 4: Kata-kata Paling Berpengaruh terhadap Sentimen', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUTPUT_PATH}orang4_analisis4_sentimen_tfidf_svm.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Grafik disimpan!")

"""📊 Interpretasi Hasil Analisis #4:

- Positive F1 = 0.96 → model sangat baik mendeteksi review positif
- Negative F1 = 0.36 & Neutral F1 = 0.14 → masih lemah untuk kelas minoritas, tapi jauh lebih baik dari 0.00 sebelum SMOTE
- SMOTE terbukti membantu — tanpa SMOTE, recall negative & neutral akan mendekati 0
- Accuracy 93% tapi yang lebih penting adalah macro avg recall = 0.63, artinya model mulai belajar mengenali ketiga kelas


Kesimpulan bisnis: Kata-kata dalam teks review bisa memprediksi sentimen, terutama untuk review positif. Kelas negatif & netral masih sulit karena jumlahnya sangat sedikit di data asli.

# Analisis #5 — Prophet (Tren 10 Tahun)
"""

print("=" * 60)
print("ANALISIS 5: TREN VOLUME REVIEW TOKOPEDIA (2015–2025)")
print("=" * 60)

# Hitung volume review per bulan
df['review_date_parsed'] = pd.to_datetime(df['review_date'], errors='coerce')
df_trend = df.groupby(df['review_date_parsed'].dt.to_period('M')) \
             .size().reset_index(name='count')
df_trend['ds'] = df_trend['review_date_parsed'].dt.to_timestamp()
df_trend = df_trend[['ds', 'count']].rename(columns={'count': 'y'})
df_trend = df_trend.dropna().sort_values('ds').reset_index(drop=True)

print(f"✅ Data tren siap: {len(df_trend)} titik data bulanan")
print(f"\n5 data pertama:")
print(df_trend.head())
print(f"\n5 data terakhir:")
print(df_trend.tail())

print("⏳ Training Prophet... (mungkin 1-2 menit)")

model_prophet = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=False,
    daily_seasonality=False,
    changepoint_prior_scale=0.3
)
model_prophet.fit(df_trend)

# Prediksi 12 bulan ke depan
future = model_prophet.make_future_dataframe(periods=12, freq='ME')
forecast = model_prophet.predict(future)

print("✅ Prophet selesai!")
print(f"\n📊 Prediksi 6 bulan ke depan:")
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(12)[['ds','yhat']].to_string(index=False))

fig1 = model_prophet.plot(forecast, figsize=(14, 5))
plt.title('Tren Volume Review Tokopedia 2015–2025 + Prediksi 12 Bulan ke Depan', fontsize=13)
plt.xlabel('Tahun')
plt.ylabel('Jumlah Review per Bulan')
plt.tight_layout()
plt.savefig(f'{OUTPUT_PATH}orang4_analisis5_prophet_tren.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Grafik tren disimpan!")

fig2 = model_prophet.plot_components(forecast, figsize=(14, 8))
plt.tight_layout()
plt.savefig(f'{OUTPUT_PATH}orang4_analisis5_prophet_komponen.png', dpi=150, bbox_inches='tight')
plt.show()

# Ringkasan tren
trend_awal = forecast[forecast['ds'].dt.year == 2015]['trend'].mean()
trend_akhir = forecast[forecast['ds'].dt.year == 2025]['trend'].mean()
pertumbuhan = ((trend_akhir - trend_awal) / trend_awal * 100)

print("✅ Grafik komponen disimpan!")
print(f"\n📊 RINGKASAN TREN:")
print(f"   Tren rata-rata 2015 : {trend_awal:.0f} review/bulan")
print(f"   Tren rata-rata 2025 : {trend_akhir:.0f} review/bulan")
print(f"   Pertumbuhan 10 tahun: {pertumbuhan:.1f}%")

"""# BAGIAN 3: Visualisasi Data
---

# 📊 Laporan Visualisasi Data

**Topik:** Analisis Temporal Tren Review dan Pola Perilaku Konsumen di Tokopedia (2015–2025)

---
**Daftar Visualisasi:**
1. 📦 Setup & Load Data
2. 🌟 Dashboard Overview (Ringkasan Statistik)
3. ⭐ Distribusi Rating Konsumen
4. 💬 Distribusi Sentimen
5. 💰 Harga & Penjualan
6. 📅 Tren Temporal Review
7. 📈 Rating vs Sentimen & Waktu
8. 🎉 Analisis Harbolnas (Desember)
9. 🤖 Performa Model ML
10. 🔮 Tren 10 Tahun + Forecast Prophet
11. 🗺️ Dashboard Interaktif (Plotly)

## 📦 1. Setup & Load Data
"""

# Install library tambahan untuk visualisasi interaktif
!pip install plotly kaleido wordcloud --quiet
print('✅ Library tambahan berhasil diinstall!')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Styling global untuk matplotlib
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.size'] = 11
sns.set_style('whitegrid')
sns.set_palette('husl')

# Warna tema konsisten
WARNA_SENTIMEN = {'positive': '#2ecc71', 'neutral': '#95a5a6', 'negative': '#e74c3c'}
WARNA_UTAMA = '#3498db'
WARNA_AKSEN = '#e67e22'

print('✅ Semua library berhasil diimport!')
print('🎨 Setting visualisasi siap!')

# ============================================================
# LOAD DATA
# Pilih salah satu cara di bawah ini sesuai situasimu:
# ============================================================

# OPSI A: Upload manual dari komputer (paling mudah)
from google.colab import files
print('⬆️  Silakan upload file clean_tokopedia_reviews.csv')
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# ---
# OPSI B: Dari Google Drive (uncomment jika pakai Drive)
# from google.colab import drive
# drive.mount('/content/drive')
# DATA_PATH = '/content/drive/MyDrive/Project_BigData_Kel2 (1)/clean_tokopedia_reviews.csv'
# df = pd.read_csv(DATA_PATH)
# ---

# Pastikan kolom tanggal sudah parsed
df['review_date'] = pd.to_datetime(df['review_date'], errors='coerce')
if 'year' not in df.columns:
    df['year'] = df['review_date'].dt.year
if 'month' not in df.columns:
    df['month'] = df['review_date'].dt.month
if 'quarter' not in df.columns:
    df['quarter'] = df['review_date'].dt.to_period('Q').astype(str)
if 'day_of_week' not in df.columns:
    df['day_of_week'] = df['review_date'].dt.day_name()
if 'sentiment_label' in df.columns:
    df['sentiment_label'] = df['sentiment_label'].astype(str).str.lower().str.strip()

print(f'✅ Dataset berhasil dimuat!')
print(f'   Jumlah baris : {df.shape[0]:,}')
print(f'   Jumlah kolom : {df.shape[1]}')
print(f'   Kolom        : {list(df.columns)}')
df.head(3)

"""---
## 🌟 2. Dashboard Overview — Ringkasan Statistik Utama
"""

# ============================================================
# VISUALISASI 1: DASHBOARD OVERVIEW (KPI Cards + Summary)
# ============================================================
fig = plt.figure(figsize=(16, 8))
gs = gridspec.GridSpec(2, 4, figure=fig, hspace=0.5, wspace=0.4)

# --- KPI CARDS (baris atas) ---
kpi_data = [
    ('Total Review', f"{df.shape[0]:,}", '📝', '#3498db'),
    ('Rata-rata Rating', f"{df['rating'].mean():.2f} ⭐", '⭐', '#f39c12'),
    ('Review Positif', f"{(df['sentiment_label']=='positive').sum():,}", '😊', '#2ecc71'),
    ('Produk Unik', f"{df['product_name'].nunique():,}" if 'product_name' in df.columns else 'N/A', '📦', '#9b59b6'),
]

for i, (label, value, emoji, color) in enumerate(kpi_data):
    ax = fig.add_subplot(gs[0, i])
    ax.set_facecolor(color + '22')  # warna transparan
    ax.text(0.5, 0.65, value, ha='center', va='center', fontsize=18,
            fontweight='bold', color=color, transform=ax.transAxes)
    ax.text(0.5, 0.25, label, ha='center', va='center', fontsize=10,
            color='gray', transform=ax.transAxes)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_edgecolor(color)
        spine.set_linewidth(2)

# --- DISTRIBUSI RATING (baris bawah kiri) ---
ax5 = fig.add_subplot(gs[1, :2])
rating_counts = df['rating'].value_counts().sort_index()
bars = ax5.bar(rating_counts.index, rating_counts.values,
               color=['#e74c3c','#e67e22','#f1c40f','#2ecc71','#3498db'],
               edgecolor='white', linewidth=1.5)
for bar, val in zip(bars, rating_counts.values):
    ax5.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 30,
             f'{val:,}', ha='center', fontsize=9, fontweight='bold')
ax5.set_title('Distribusi Rating Konsumen', fontweight='bold', fontsize=12)
ax5.set_xlabel('Bintang')
ax5.set_ylabel('Jumlah Review')
ax5.tick_params(axis='x', rotation=0)

# --- DISTRIBUSI SENTIMEN (baris bawah kanan) ---
ax6 = fig.add_subplot(gs[1, 2:])
sent_counts = df['sentiment_label'].value_counts()
colors_sent = [WARNA_SENTIMEN.get(k, 'gray') for k in sent_counts.index]
wedges, texts, autotexts = ax6.pie(
    sent_counts.values,
    labels=[s.capitalize() for s in sent_counts.index],
    autopct='%1.1f%%',
    colors=colors_sent,
    startangle=90,
    wedgeprops={'edgecolor': 'white', 'linewidth': 2}
)
for autotext in autotexts:
    autotext.set_fontweight('bold')
ax6.set_title('Distribusi Sentimen', fontweight='bold', fontsize=12)

fig.suptitle('📊 Dashboard Overview — Tokopedia Review Analysis 2015–2025',
             fontsize=15, fontweight='bold', y=1.01)
plt.savefig('viz1_dashboard_overview.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 1: Dashboard Overview selesai!')

"""---
## ⭐ 3. Distribusi Rating — Detail
"""

# ============================================================
# VISUALISASI 2: DISTRIBUSI RATING (Bar + Pie + Kumulatif)
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

rating_counts = df['rating'].value_counts().sort_index()
rating_pct = rating_counts / rating_counts.sum() * 100
star_colors = ['#e74c3c', '#e67e22', '#f1c40f', '#2ecc71', '#27ae60']

# Bar chart dengan label persen
bars = axes[0].bar(rating_counts.index, rating_counts.values,
                    color=star_colors, edgecolor='white', linewidth=1.5)
for bar, pct in zip(bars, rating_pct.values):
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + max(rating_counts)*0.01,
                 f'{pct:.1f}%', ha='center', fontsize=9, fontweight='bold')
axes[0].set_title('Frekuensi Rating', fontweight='bold')
axes[0].set_xlabel('Rating (Bintang)')
axes[0].set_ylabel('Jumlah Review')

# Donut chart
wedges, texts, autotexts = axes[1].pie(
    rating_counts.values,
    labels=[f'⭐{r}' for r in rating_counts.index],
    autopct='%1.1f%%',
    colors=star_colors,
    startangle=90,
    wedgeprops={'width': 0.6, 'edgecolor': 'white', 'linewidth': 2}
)
axes[1].set_title('Proporsi Rating', fontweight='bold')
axes[1].text(0, 0, f'{rating_counts.get(5,0)/rating_counts.sum()*100:.0f}%\n⭐5',
             ha='center', va='center', fontsize=13, fontweight='bold')

# Kumulatif (puas = rating >= 4)
puas = df[df['rating'] >= 4].shape[0]
tidak_puas = df[df['rating'] < 4].shape[0]
axes[2].bar(['Puas (≥4⭐)', 'Tidak Puas (<4⭐)'], [puas, tidak_puas],
            color=['#27ae60', '#e74c3c'], edgecolor='white', linewidth=1.5)
axes[2].text(0, puas + max(puas,tidak_puas)*0.01,
             f'{puas/df.shape[0]*100:.1f}%', ha='center', fontweight='bold')
axes[2].text(1, tidak_puas + max(puas,tidak_puas)*0.01,
             f'{tidak_puas/df.shape[0]*100:.1f}%', ha='center', fontweight='bold')
axes[2].set_title('Segmen Kepuasan Konsumen', fontweight='bold')
axes[2].set_ylabel('Jumlah Review')

fig.suptitle('⭐ Analisis Distribusi Rating Konsumen Tokopedia',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz2_distribusi_rating.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 2: Distribusi Rating selesai!')

"""---
## 💬 4. Distribusi Sentimen
"""

# ============================================================
# VISUALISASI 3: DISTRIBUSI SENTIMEN + SENTIMEN PER TAHUN
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Bar chart sentimen dengan annotasi
sent_counts = df['sentiment_label'].value_counts()
colors_sent = [WARNA_SENTIMEN.get(k, '#bdc3c7') for k in sent_counts.index]
bars = axes[0].bar(sent_counts.index, sent_counts.values,
                    color=colors_sent, edgecolor='white', linewidth=2)
for bar, val in zip(bars, sent_counts.values):
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + max(sent_counts)*0.02,
                 f'{val:,}\n({val/sent_counts.sum()*100:.1f}%)',
                 ha='center', fontsize=10, fontweight='bold')
axes[0].set_title('Distribusi Sentimen Label', fontweight='bold', fontsize=12)
axes[0].set_xlabel('Sentimen')
axes[0].set_ylabel('Jumlah Review')
axes[0].tick_params(axis='x', labelsize=11)

# Sentimen per tahun (stacked bar)
if df['year'].notna().any():
    sent_tahun = df.groupby(['year', 'sentiment_label']).size().unstack(fill_value=0)
    sent_tahun_pct = sent_tahun.div(sent_tahun.sum(axis=1), axis=0) * 100
    order = ['positive', 'neutral', 'negative']
    cols_available = [c for c in order if c in sent_tahun_pct.columns]
    bar_colors = [WARNA_SENTIMEN[c] for c in cols_available]
    sent_tahun_pct[cols_available].plot(
        kind='bar', stacked=True, ax=axes[1],
        color=bar_colors, edgecolor='white', linewidth=0.5
    )
    axes[1].set_title('Proporsi Sentimen per Tahun (%)', fontweight='bold', fontsize=12)
    axes[1].set_xlabel('Tahun')
    axes[1].set_ylabel('Persentase (%)')
    axes[1].tick_params(axis='x', rotation=45)
    axes[1].legend(title='Sentimen', loc='lower right')
    axes[1].set_ylim(0, 110)

fig.suptitle('💬 Analisis Distribusi Sentimen Konsumen', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz3_distribusi_sentimen.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 3: Distribusi Sentimen selesai!')

"""---
## 💰 5. Distribusi Harga & Penjualan
"""

# ============================================================
# VISUALISASI 4: HARGA & PENJUALAN (KDE + Boxplot + Scatter)
# ============================================================
fig, axes = plt.subplots(2, 3, figsize=(16, 10))

df95 = df[df['product_price'] < df['product_price'].quantile(0.95)]
df95s = df[df['sold_count'] < df['sold_count'].quantile(0.95)]

# KDE Harga
sns.histplot(df95['product_price'], kde=True, ax=axes[0][0],
             color=WARNA_UTAMA, bins=40)
axes[0][0].set_title('Distribusi Harga Produk', fontweight='bold')
axes[0][0].set_xlabel('Harga (Rp)')
axes[0][0].axvline(df['product_price'].median(), color='red',
                    linestyle='--', label=f'Median: Rp{df["product_price"].median():,.0f}')
axes[0][0].legend(fontsize=9)

# Boxplot Harga per Rating
df95.boxplot(column='product_price', by='rating', ax=axes[0][1])
axes[0][1].set_title('Harga per Rating', fontweight='bold')
axes[0][1].set_xlabel('Rating (Bintang)')
axes[0][1].set_ylabel('Harga (Rp)')
plt.sca(axes[0][1]); plt.title('Harga per Rating')

# Rata-rata Harga per Rating
avg_price_rating = df.groupby('rating')['product_price'].mean()
axes[0][2].bar(avg_price_rating.index, avg_price_rating.values,
               color='steelblue', edgecolor='white')
axes[0][2].set_title('Rata-rata Harga per Rating', fontweight='bold')
axes[0][2].set_xlabel('Rating')
axes[0][2].set_ylabel('Rata-rata Harga (Rp)')
for i, v in enumerate(avg_price_rating.values):
    axes[0][2].text(i+1, v + avg_price_rating.max()*0.02,
                    f'Rp{v/1000:.0f}K', ha='center', fontsize=8)

# KDE Sold Count
sns.histplot(df95s['sold_count'], kde=True, ax=axes[1][0],
             color=WARNA_AKSEN, bins=40)
axes[1][0].set_title('Distribusi Jumlah Penjualan', fontweight='bold')
axes[1][0].set_xlabel('Sold Count')
axes[1][0].axvline(df['sold_count'].median(), color='red',
                    linestyle='--', label=f'Median: {df["sold_count"].median():,.0f}')
axes[1][0].legend(fontsize=9)

# Sold Count per Sentimen
avg_sold_sent = df.groupby('sentiment_label')['sold_count'].mean()
colors_s = [WARNA_SENTIMEN.get(k, 'gray') for k in avg_sold_sent.index]
axes[1][1].bar(avg_sold_sent.index, avg_sold_sent.values,
               color=colors_s, edgecolor='white')
axes[1][1].set_title('Rata-rata Penjualan per Sentimen', fontweight='bold')
axes[1][1].set_xlabel('Sentimen')
axes[1][1].set_ylabel('Rata-rata Sold Count')

# Insight korelasi: Harga vs Sold Count
sample = df95.sample(min(2000, len(df95)), random_state=42)
sent_color = [WARNA_SENTIMEN.get(s, 'gray') for s in sample['sentiment_label']]
axes[1][2].scatter(sample['product_price'], sample['sold_count'],
                    c=sent_color, alpha=0.4, s=15)
axes[1][2].set_title('Harga vs Penjualan', fontweight='bold')
axes[1][2].set_xlabel('Harga (Rp)')
axes[1][2].set_ylabel('Sold Count')
from matplotlib.patches import Patch
legend_els = [Patch(fc=c, label=k.capitalize()) for k, c in WARNA_SENTIMEN.items()]
axes[1][2].legend(handles=legend_els, fontsize=8, title='Sentimen')

fig.suptitle('💰 Analisis Harga & Penjualan Produk Tokopedia',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz4_harga_penjualan.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 4: Harga & Penjualan selesai!')

"""---
## 📅 6. Tren Temporal Review
"""

# ============================================================
# VISUALISASI 5: TREN TEMPORAL (Per Tahun, Bulan, Hari, Quarter)
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(16, 10))

# Review per Tahun
rev_tahun = df.groupby('year').size()
axes[0][0].bar(rev_tahun.index, rev_tahun.values, color=WARNA_UTAMA,
               edgecolor='white', linewidth=1.5)
axes[0][0].plot(rev_tahun.index, rev_tahun.values, 'o-',
                color=WARNA_AKSEN, linewidth=2, markersize=6)
axes[0][0].set_title('Jumlah Review per Tahun (2015–2025)', fontweight='bold')
axes[0][0].set_xlabel('Tahun')
axes[0][0].set_ylabel('Jumlah Review')
axes[0][0].tick_params(axis='x', rotation=45)

# Review per Bulan
rev_bulan = df.groupby('month').size()
bulan_label = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
colors_bulan = ['#e74c3c' if m == 12 else WARNA_UTAMA for m in range(1, 13)]
axes[0][1].bar(range(1, 13), rev_bulan.reindex(range(1,13), fill_value=0).values,
               color=colors_bulan, edgecolor='white')
axes[0][1].set_xticks(range(1, 13))
axes[0][1].set_xticklabels(bulan_label, rotation=45)
axes[0][1].set_title('Distribusi Review per Bulan\n(Merah = Desember/Harbolnas)', fontweight='bold')
axes[0][1].set_ylabel('Jumlah Review')

# Review per Hari dalam Seminggu
urutan_hari = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
label_hari = ['Sen','Sel','Rab','Kam','Jum','Sab','Min']
rev_hari = df['day_of_week'].value_counts().reindex(urutan_hari, fill_value=0)
wknd_colors = ['#e74c3c' if h in ['Saturday','Sunday'] else WARNA_UTAMA for h in urutan_hari]
axes[1][0].bar(label_hari, rev_hari.values, color=wknd_colors, edgecolor='white')
axes[1][0].set_title('Review per Hari dalam Seminggu\n(Merah = Weekend)', fontweight='bold')
axes[1][0].set_ylabel('Jumlah Review')

# Heatmap Review per Tahun x Bulan
pivot = df.groupby(['year', 'month']).size().unstack(fill_value=0)
pivot.columns = bulan_label[:len(pivot.columns)]
sns.heatmap(pivot, ax=axes[1][1], cmap='YlOrRd', fmt='d',
            linewidths=0.5, linecolor='white', annot=len(pivot) <= 12)
axes[1][1].set_title('Heatmap Volume Review (Tahun × Bulan)', fontweight='bold')
axes[1][1].set_xlabel('Bulan')
axes[1][1].set_ylabel('Tahun')

fig.suptitle('📅 Analisis Tren Temporal Review Tokopedia',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz5_tren_temporal.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 5: Tren Temporal selesai!')

"""---
## 📈 7. Rating vs Sentimen & Waktu
"""

# ============================================================
# VISUALISASI 6: RATING vs SENTIMEN & WAKTU
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Violin plot rating per sentimen
order_sent = ['negative', 'neutral', 'positive']
colors_v = [WARNA_SENTIMEN[k] for k in order_sent]
df_v = df[df['sentiment_label'].isin(order_sent)]
parts = axes[0].violinplot(
    [df_v[df_v['sentiment_label']==s]['rating'].dropna().values for s in order_sent],
    positions=range(len(order_sent)), showmedians=True
)
for i, (pc, col) in enumerate(zip(parts['bodies'], colors_v)):
    pc.set_facecolor(col)
    pc.set_alpha(0.7)
axes[0].set_xticks(range(len(order_sent)))
axes[0].set_xticklabels([s.capitalize() for s in order_sent])
axes[0].set_title('Distribusi Rating per Sentimen\n(Violin Plot)', fontweight='bold')
axes[0].set_ylabel('Rating')

# Rata-rata Rating per Sentimen (bar + error bar)
avg_r = df_v.groupby('sentiment_label')['rating'].agg(['mean', 'std'])
avg_r = avg_r.reindex(order_sent)
bars = axes[1].bar(range(len(order_sent)), avg_r['mean'],
                    yerr=avg_r['std'], capsize=5,
                    color=colors_v, edgecolor='white', error_kw={'linewidth': 2})
axes[1].set_xticks(range(len(order_sent)))
axes[1].set_xticklabels([s.capitalize() for s in order_sent])
axes[1].set_ylim(0, 6.5)
for i, v in enumerate(avg_r['mean']):
    axes[1].text(i, v + avg_r['std'].iloc[i] + 0.1, f'{v:.2f}',
                 ha='center', fontweight='bold')
axes[1].set_title('Rata-rata Rating per Sentimen\n(± Standar Deviasi)', fontweight='bold')
axes[1].set_ylabel('Rata-rata Rating')

# Line chart: Rata-rata rating per tahun
avg_r_tahun = df.groupby('year')['rating'].mean()
axes[2].plot(avg_r_tahun.index, avg_r_tahun.values,
             'o-', color=WARNA_UTAMA, linewidth=2.5, markersize=8, markerfacecolor='white',
             markeredgewidth=2)
axes[2].fill_between(avg_r_tahun.index, avg_r_tahun.values,
                      alpha=0.1, color=WARNA_UTAMA)
axes[2].set_ylim(avg_r_tahun.min() - 0.2, avg_r_tahun.max() + 0.2)
axes[2].set_title('Tren Rata-rata Rating per Tahun', fontweight='bold')
axes[2].set_xlabel('Tahun')
axes[2].set_ylabel('Rata-rata Rating')
axes[2].grid(True, linestyle='--', alpha=0.5)
for x, y in zip(avg_r_tahun.index, avg_r_tahun.values):
    axes[2].annotate(f'{y:.2f}', (x, y), textcoords='offset points',
                     xytext=(0, 8), ha='center', fontsize=8)

fig.suptitle('📈 Hubungan Rating, Sentimen & Waktu', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz6_rating_sentimen_waktu.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 6: Rating vs Sentimen & Waktu selesai!')

"""---
## 🎉 8. Analisis Harbolnas
"""

# ============================================================
# VISUALISASI 7: HARBOLNAS vs NON-HARBOLNAS
# Sumber: Hasil Mann-Whitney U Test
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

rating_des = df[df['month'] == 12]['rating']
rating_non = df[df['month'] != 12]['rating']

# Bar: Rata-rata rating per bulan dengan highlight Desember
avg_monthly = df.groupby('month')['rating'].mean()
bulan_label = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
colors_m = ['#e74c3c' if m == 12 else WARNA_UTAMA for m in range(1, 13)]
axes[0].bar(range(1, 13), avg_monthly.reindex(range(1,13)).values,
            color=colors_m, edgecolor='white')
axes[0].set_xticks(range(1, 13))
axes[0].set_xticklabels(bulan_label, rotation=45)
axes[0].axhline(avg_monthly.mean(), color='orange', linestyle='--',
                 linewidth=2, label=f'Rata-rata: {avg_monthly.mean():.3f}')
axes[0].set_title('Rata-rata Rating per Bulan\n(Merah = Harbolnas Des)', fontweight='bold')
axes[0].set_ylabel('Rata-rata Rating')
axes[0].legend(fontsize=9)
ylim = axes[0].get_ylim()
axes[0].set_ylim(ylim[0], ylim[1] + 0.05)

# Grouped bar: distribusi rating Des vs non-Des
des_pct = rating_des.value_counts(normalize=True).sort_index() * 100
non_pct = rating_non.value_counts(normalize=True).sort_index() * 100
x = np.arange(1, 6)
axes[1].bar(x - 0.2, des_pct.reindex(range(1,6), fill_value=0).values,
            0.38, label='Desember (Harbolnas)', color='#e74c3c', alpha=0.8)
axes[1].bar(x + 0.2, non_pct.reindex(range(1,6), fill_value=0).values,
            0.38, label='Bukan Desember', color=WARNA_UTAMA, alpha=0.8)
axes[1].set_xticks(x)
axes[1].set_title('Distribusi Rating: Harbolnas vs Bulan Lain', fontweight='bold')
axes[1].set_xlabel('Rating (Bintang)')
axes[1].set_ylabel('Persentase (%)')
axes[1].legend()

# Kesimpulan statistik (p = 0.1159, tidak signifikan)
axes[2].set_xlim(0, 1)
axes[2].set_ylim(0, 1)
axes[2].axis('off')
insight_text = (
    "🔬 HASIL UJI MANN-WHITNEY U\n"
    f"📊 Mean Rating Desember:\n   {rating_des.mean():.3f}\n\n"
    f"📊 Mean Rating Non-Des:\n   {rating_non.mean():.3f}\n\n"
    "📈 P-value = 0.1159\n\n"
    "✅ KESIMPULAN:\n"
    "Tidak ada penurunan\n"
    "signifikan kepuasan\n"
    "saat Harbolnas!\n\n"
    "Tokopedia berhasil\n"
    "menjaga kualitas\nlayanan di peak season."
)
axes[2].text(0.5, 0.5, insight_text, ha='center', va='center',
             fontsize=11, transform=axes[2].transAxes,
             bbox=dict(boxstyle='round,pad=0.5', facecolor='#eaf4fb',
                       edgecolor=WARNA_UTAMA, linewidth=2))

fig.suptitle('🎉 Analisis Kepuasan Konsumen Saat Harbolnas (Desember)',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz7_harbolnas.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 7: Harbolnas selesai!')

"""---
## 🤖 9. Performa Model ML
"""

# ============================================================
# VISUALISASI 8: RINGKASAN PERFORMA MODEL
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# --- Analisis 1 & 3: R² Score Comparison ---
models_name = ['Linear\nRegression', 'Decision\nTree']
r2_scores = [0.000514, 0.004644]
rmse_scores = [0.4950, 0.4928]

bars = axes[0].bar(models_name, r2_scores,
                    color=['#3498db', '#e67e22'], edgecolor='white', linewidth=2)
axes[0].axhline(0, color='red', linestyle='--', linewidth=1.5,
                 label='R²=0 (Model Tidak Berguna)')
for bar, v in zip(bars, r2_scores):
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 0.0001, f'{v:.4f}',
                 ha='center', fontweight='bold', fontsize=11)
axes[0].set_title('R² Score: Prediksi Rating\ndari Harga & Penjualan', fontweight='bold')
axes[0].set_ylabel('R² Score')
axes[0].legend(fontsize=9)
axes[0].text(0.5, 0.9,
             '💡 R² ≈ 0 berarti harga &\npenjualan BUKAN penentu rating!',
             ha='center', transform=axes[0].transAxes, fontsize=9,
             color='red', style='italic')

# --- Analisis 4: SVM Klasifikasi Sentimen ---
kelas = ['Negative', 'Neutral', 'Positive']
precision = [0.42, 0.26, 0.97]
recall = [0.31, 0.09, 0.96]
f1 = [0.36, 0.13, 0.96]
x2 = np.arange(len(kelas))
width = 0.25
axes[1].bar(x2 - width, precision, width, label='Precision',
            color='#3498db', alpha=0.85)
axes[1].bar(x2, recall, width, label='Recall',
            color='#2ecc71', alpha=0.85)
axes[1].bar(x2 + width, f1, width, label='F1-Score',
            color='#e74c3c', alpha=0.85)
axes[1].set_xticks(x2)
axes[1].set_xticklabels(kelas)
axes[1].set_ylim(0, 1.2)
axes[1].set_title('Performa Model SVM+SMOTE\nKlasifikasi Sentimen', fontweight='bold')
axes[1].set_ylabel('Score')
axes[1].legend()
axes[1].axhline(0.93, color='purple', linestyle='--', linewidth=1,
                 label='Overall Accuracy: 93%')

# --- Ringkasan Insight ---
axes[2].axis('off')
summary = (
    "📋 RINGKASAN TEMUAN ANALITIK\n"
    "❌ Harga → Rating\n"
    "   Korelasi Spearman ≈ 0\n"
    "   Harga BUKAN penentu kepuasan\n\n"
    "❌ Harga + Penjualan → Rating\n"
    "   R² < 0.5% (tidak prediktif)\n\n"
    "✅ Teks Review → Sentimen\n"
    "   SVM + SMOTE Accuracy: 93%\n"
    "   Positif F1 = 0.96 (sangat baik)\n\n"
    "✅ Harbolnas (Des)\n"
    "   Kepuasan STABIL (p=0.1159)\n"
    "   Tidak ada penurunan signifikan\n\n"
    "📈 Rekomendasi:\n"
    "   Fokus ke kualitas produk &\n"
    "   pengalaman layanan, bukan harga!"
)
axes[2].text(0.05, 0.95, summary, ha='left', va='top',
             fontsize=10, transform=axes[2].transAxes,
             bbox=dict(boxstyle='round,pad=0.6', facecolor='#fef9e7',
                       edgecolor='#f39c12', linewidth=2),
             family='monospace')

fig.suptitle('🤖 Performa Model Machine Learning & Insight Analitik',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('viz8_performa_model.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualisasi 8: Performa Model selesai!')

"""---
## 🔮 10. Tren 10 Tahun + Forecast Prophet
"""

# ============================================================
# VISUALISASI 9: FORECAST PROPHET (Jalankan jika Prophet tersedia)
# ============================================================
try:
    from prophet import Prophet

    df_trend = df.groupby(df['review_date'].dt.to_period('M')) \
                 .size().reset_index(name='y')
    df_trend['ds'] = df_trend['review_date'].dt.to_timestamp()
    df_trend = df_trend[['ds','y']].dropna().sort_values('ds').reset_index(drop=True)

    model_p = Prophet(yearly_seasonality=True, weekly_seasonality=False,
                      daily_seasonality=False, changepoint_prior_scale=0.3)
    model_p.fit(df_trend)
    future = model_p.make_future_dataframe(periods=12, freq='ME')
    forecast = model_p.predict(future)

    fig, axes = plt.subplots(2, 1, figsize=(14, 10))

    # Plot tren utama
    axes[0].plot(df_trend['ds'], df_trend['y'], 'o', color='gray',
                 alpha=0.6, markersize=4, label='Data Aktual')
    axes[0].plot(forecast['ds'], forecast['yhat'], '-',
                 color=WARNA_UTAMA, linewidth=2.5, label='Prediksi Prophet')
    axes[0].fill_between(forecast['ds'], forecast['yhat_lower'],
                          forecast['yhat_upper'], alpha=0.2, color=WARNA_UTAMA,
                          label='Confidence Interval')
    # Tandai area forecast
    axes[0].axvline(df_trend['ds'].max(), color='red', linestyle='--',
                     linewidth=2, label='Batas Data Aktual')
    axes[0].set_title('Tren Volume Review Tokopedia 2015–2025\n+ Prediksi 12 Bulan ke Depan (Prophet)',
                       fontweight='bold', fontsize=13)
    axes[0].set_ylabel('Jumlah Review per Bulan')
    axes[0].legend()

    # Komponen tren
    trend_data = forecast[['ds','trend']]
    axes[1].plot(trend_data['ds'], trend_data['trend'],
                 color=WARNA_AKSEN, linewidth=2.5)
    axes[1].fill_between(trend_data['ds'], trend_data['trend'],
                          alpha=0.15, color=WARNA_AKSEN)
    axes[1].set_title('Komponen Tren Jangka Panjang', fontweight='bold', fontsize=12)
    axes[1].set_ylabel('Tren Review')
    axes[1].set_xlabel('Tahun')

    fig.suptitle('🔮 Analisis Tren 10 Tahun & Forecast Review Tokopedia',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig('viz9_prophet_forecast.png', dpi=150, bbox_inches='tight')
    plt.show()
    print('✅ Visualisasi 9: Prophet Forecast selesai!')

except Exception as e:
    print(f'⚠️  Prophet tidak tersedia atau error: {e}')
    print('   Jalankan: !pip install prophet terlebih dahulu')
    print('   Lanjut ke visualisasi berikutnya...')

"""---
## 🗺️ 11. Dashboard Interaktif dengan Plotly
"""

# ============================================================
# VISUALISASI 10: DASHBOARD INTERAKTIF (PLOTLY)
# ============================================================
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
    rows=2, cols=3,
    subplot_titles=[
        '⭐ Distribusi Rating',
        '💬 Distribusi Sentimen',
        '📅 Review per Tahun',
        '📆 Review per Bulan',
        '💰 Rata-rata Harga per Rating',
        '📊 Sentimen per Tahun (%)',
    ],
    specs=[
        [{'type': 'bar'}, {'type': 'pie'}, {'type': 'bar'}],
        [{'type': 'bar'}, {'type': 'bar'}, {'type': 'bar'}],
    ]
)

# [1,1] Rating Distribution
rc = df['rating'].value_counts().sort_index()
fig.add_trace(go.Bar(x=rc.index.astype(str), y=rc.values,
    marker_color=['#e74c3c','#e67e22','#f1c40f','#2ecc71','#27ae60'],
    name='Rating', showlegend=False), row=1, col=1)

# [1,2] Pie Sentimen
sc = df['sentiment_label'].value_counts()
fig.add_trace(go.Pie(labels=sc.index, values=sc.values,
    marker_colors=[WARNA_SENTIMEN.get(k, '#bdc3c7') for k in sc.index],
    hole=0.4, name='Sentimen'), row=1, col=2)

# [1,3] Review per tahun
rt = df.groupby('year').size().reset_index(name='count')
fig.add_trace(go.Bar(x=rt['year'], y=rt['count'],
    marker_color='#3498db', name='Review/Tahun', showlegend=False), row=1, col=3)

# [2,1] Review per bulan
rm = df.groupby('month').size().reindex(range(1,13), fill_value=0)
bulan_label = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
fig.add_trace(go.Bar(x=bulan_label, y=rm.values,
    marker_color=['#e74c3c' if i==11 else '#3498db' for i in range(12)],
    name='Review/Bulan', showlegend=False), row=2, col=1)

# [2,2] Rata-rata Harga per Rating
ap = df.groupby('rating')['product_price'].mean()
fig.add_trace(go.Bar(x=ap.index.astype(str), y=ap.values,
    marker_color='steelblue', name='Avg Harga', showlegend=False), row=2, col=2)

# [2,3] Sentimen per tahun stacked
sty = df.groupby(['year', 'sentiment_label']).size().unstack(fill_value=0)
for sent, color in WARNA_SENTIMEN.items():
    if sent in sty.columns:
        sty_pct = sty[sent] / sty.sum(axis=1) * 100
        fig.add_trace(go.Bar(x=sty.index, y=sty_pct.values,
            name=sent.capitalize(), marker_color=color), row=2, col=3)

fig.update_layout(
    title_text='📊 Dashboard Interaktif — Tokopedia Review Analysis 2015–2025',
    title_font_size=16,
    barmode='stack',
    height=700,
    template='plotly_white',
    showlegend=True
)
fig.show()
fig.write_html('viz10_dashboard_interaktif.html')
print('✅ Visualisasi 10: Dashboard Interaktif selesai!')
print('   📁 Tersimpan sebagai viz10_dashboard_interaktif.html')

"""---
## 📥 12. Download Semua Visualisasi
"""

# ============================================================
# DOWNLOAD SEMUA FILE VISUALISASI SEKALIGUS
# ============================================================
import os
import zipfile
from google.colab import files

output_files = [
    'viz1_dashboard_overview.png',
    'viz2_distribusi_rating.png',
    'viz3_distribusi_sentimen.png',
    'viz4_harga_penjualan.png',
    'viz5_tren_temporal.png',
    'viz6_rating_sentimen_waktu.png',
    'viz7_harbolnas.png',
    'viz8_performa_model.png',
    'viz9_prophet_forecast.png',
    'viz10_dashboard_interaktif.html',
]

zip_name = 'Visualisasi_Tokopedia.zip'
with zipfile.ZipFile(zip_name, 'w') as zf:
    for f_name in output_files:
        if os.path.exists(f_name):
            zf.write(f_name)
            print(f'  ✅ {f_name} ditambahkan')
        else:
            print(f'  ⚠️  {f_name} belum ada (cell belum dijalankan?)')

print(f'\n📦 ZIP berhasil dibuat: {zip_name}')
files.download(zip_name)
print('✅ Download dimulai!')

"""---
## ✅ Ringkasan Temuan Visual

| No | Visualisasi | Insight Utama |
|---|---|---|
| 1 | Dashboard Overview | ~93% review punya rating 4-5 ⭐ |
| 2 | Distribusi Rating | Mayoritas konsumen **puas** (rating 5) |
| 3 | Distribusi Sentimen | Sentimen positif dominan (>80%) |
| 4 | Harga & Penjualan | Harga bervariasi, tidak linear dengan rating |
| 5 | Tren Temporal | Volume review naik signifikan dari 2015–2025 |
| 6 | Rating vs Waktu | Rating stabil tinggi sepanjang waktu |
| 7 | Harbolnas | **Kepuasan tetap stabil** saat Harbolnas Desember |
| 8 | Performa Model | Teks review bisa prediksi sentimen (F1 positif = 0.96) |
| 9 | Forecast Prophet | Tren review terus meningkat ke depan |
| 10 | Dashboard Interaktif | Semua insight dalam satu tampilan |

**Kesimpulan Utama:** Tokopedia menunjukkan tren kepuasan konsumen yang **sangat positif dan stabil** dari 2015–2025, tidak dipengaruhi harga produk maupun musim belanja, dan model NLP dapat mengidentifikasi sentimen dari teks review dengan sangat baik.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # 1. Konfigurasi Halaman & Tema
# st.set_page_config(
#     page_title="Tokopedia Consumer Insight Dashboard",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # Custom CSS untuk mempercantik tampilan kartu indikator
# st.markdown("""
#     <style>
#     .metric-box {
#         background-color: #f8f9fa;
#         padding: 20px;
#         border-radius: 10px;
#         border-left: 5px solid #28a745;
#         box-shadow: 2px 2px 5px rgba(0,0,0,0.05);
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# # 2. Memuat Data dari Session Storage
# @st.cache_data
# def load_data():
#     # Pastikan file ini sudah ada di session storage Colab Anda
#     df = pd.read_csv('clean_tokopedia_reviews.csv')
#     df['review_date'] = pd.to_datetime(df['review_date'])
#     df['year'] = df['review_date'].dt.year
#     df['month'] = df['review_date'].dt.month
#     return df
# 
# try:
#     df = load_data()
# except FileNotFoundError:
#     st.error("❌ File 'clean_tokopedia_reviews.csv' tidak ditemukan. Silakan upload terlebih dahulu ke panel kiri Colab.")
#     st.stop()
# 
# # 3. Header Dashboard
# st.title("📊 Tokopedia Consumer Insight Dashboard (2015–2025)")
# st.markdown("---")
# 
# # 4. Ringkasan Eksekutif (KPI Cards untuk Insight Instan)
# st.subheader("📌 Ringkasan Performa Utama")
# kpi1, kpi2, kpi3, kpi4 = st.columns(4)
# 
# with kpi1:
#     st.markdown(f"<div class='metric-box'><h5>Total Ulasan Dinalisis</h5><h2>{len(df):,}</h2><p style='color:gray;'>Volume Data Big Data</p></div>", unsafe_allow_html=True)
# with kpi2:
#     avg_rating = df['rating'].mean()
#     st.markdown(f"<div class='metric-box'><h5>Rata-rata Rating</h5><h2>{avg_rating:.2f} / 5.0</h2><p style='color:green;'>Sangat Puas ⭐</p></div>", unsafe_allow_html=True)
# with kpi3:
#     # Mengambil proporsi rating 5 dari temuan EDA
#     prop_bintang_5 = (df['rating'] == 5).mean() * 100
#     st.markdown(f"<div class='metric-box'><h5>Dominasi Bintang 5</h5><h2>{prop_bintang_5:.1f}%</h2><p style='color:blue;'>Mayoritas Mutlak</p></div>", unsafe_allow_html=True)
# with kpi4:
#     st.markdown("<div class='metric-box'><h5>Akurasi Model AI</h5><h2>96.0%</h2><p style='color:purple;'>F1-Score Sentimen Positif</p></div>", unsafe_allow_html=True)
# 
# st.markdown("<br>", unsafe_allow_html=True)
# 
# # 5. Pembagian Tab Berdasarkan Sudut Pandang Bisnis
# tab1, tab2, tab3 = st.tabs(["📈 Tren & Keterlibatan", "⚖️ Analisis Faktor & Hipotesis", "🤖 Prediksi & AI Insight"])
# 
# # --- TAB 1: TREN & KETERLIBATAN CONSUMER ---
# with tab1:
#     st.header("Analisis Tren Temporal Ekonomi Digital")
#     col_a, col_b = st.columns([2, 1])
# 
#     with col_a:
#         tren_tahun = df.groupby('year').size().reset_index(name='Jumlah Review')
#         fig_trend = px.line(tren_tahun, x='year', y='Jumlah Review', markers=True,
#                             title='Pertumbuhan Volume Ulasan Tahunan',
#                             labels={'year': 'Tahun', 'Jumlah Review': 'Volume Transaksi/Ulasan'})
#         fig_trend.update_traces(line_color='#28a745', marker=dict(size=8))
#         st.plotly_chart(fig_trend, use_container_width=True)
# 
#     with col_b:
#         st.markdown("""
#         ### 💡 Insight Bisnis untuk Manajemen:
#         * **Akselerasi Digital (Pasca-2020):** Lonjakan masif ulasan mengonfirmasi pergeseran perilaku konsumen yang makin bergantung pada e-commerce sejak pandemi.
#         * **Kematangan Pasar (2024-2025):** Aktivitas mencapai puncaknya, menandakan ekosistem Tokopedia telah menjadi bagian dari rutinitas harian konsumen.
#         """)
# 
# # --- TAB 2: ANALISIS FAKTOR & HIPOTESIS ---
# with tab2:
#     st.header("Pengujian Asumsi & Hipotesis Operasional")
# 
#     col_c, col_d = st.columns(2)
# 
#     with col_c:
#         st.subheader("1. Pengaruh Harga Terhadap Kepuasan")
#         avg_price = df.groupby('rating')['product_price'].mean().reset_index()
#         fig_harga = px.bar(avg_price, x='rating', y='product_price',
#                            title='Rata-rata Harga Produk per Skala Rating',
#                            labels={'product_price': 'Rata-rata Harga (Rp)', 'rating': 'Rating'},
#                            color_discrete_sequence=['#ffc107'])
#         st.plotly_chart(fig_harga, use_container_width=True)
#         st.info("💡 **Hasil Statistik:** Korelasi Spearman sangat lemah (rho = 0.03). Kepuasan pelanggan bersifat independen terhadap harga barang.")
# 
#     with col_d:
#         st.subheader("2. Ketangguhan Layanan Saat Harbolnas")
#         avg_rating_month = df.groupby('month')['rating'].mean().reset_index()
#         avg_rating_month['Keterangan'] = avg_rating_month['month'].apply(lambda x: 'Harbolnas (Desember)' if x == 12 else 'Bulan Biasa')
# 
#         fig_harbolnas = px.bar(avg_rating_month, x='month', y='rating', color='Keterangan',
#                                title='Stabilitas Rating Bulanan',
#                                color_discrete_map={'Harbolnas (Desember)': '#dc3545', 'Bulan Biasa': '#007bff'})
#         fig_harbolnas.update_layout(yaxis_range=[4.5, 5.0])
#         st.plotly_chart(fig_harbolnas, use_container_width=True)
#         st.info("💡 **Hasil Statistik:** Uji Mann-Whitney membuktikan tidak ada penurunan kepuasan yang signifikan di bulan Desember meskipun terjadi lonjakan beban operasional.")
# 
# # --- TAB 3: PREDIKSI & AI INSIGHT ---
# with tab3:
#     st.header("Implementasi Advanced Analytics & Machine Learning")
# 
#     col_e, col_f = st.columns(2)
# 
#     with col_e:
#         st.subheader("Klasifikasi Sentimen Berbasis Teks (SVM)")
#         st.markdown("""
#         Model kecerdasan buatan dilatih menggunakan algoritma *Support Vector Machine* (SVM) untuk membaca ulasan tekstual konsumen secara otomatis.
# 
#         * **Akurasi Sentimen Positif:** **96% (F1-Score)**
#         * **Rekomendasi Operasional:** Perusahaan dapat memanfaatkan model ini untuk melakukan *real-time flagging* pada ulasan yang masuk tanpa perlu validasi manual oleh tim CS.
#         """)
# 
#     with col_f:
#         st.subheader("Forecasting Tren Masa Depan (Prophet)")
#         st.markdown("""
#         Melalui pemodelan *Time Series Forecasting* menggunakan algoritma Prophet, tren volume interaksi diproyeksikan akan terus mengalami pertumbuhan positif.
# 
#         * **Rekomendasi Infrastruktur:** Tim IT dan operasional disarankan untuk meningkatkan kapasitas server dan memperkuat kemitraan logistik menjelang kuartal akhir guna mengantisipasi pertumbuhan volume yang diprediksi meningkat.
#         """)

import urllib
print("🔑 PASSWORD UNTUK LOCAL TUNNEL (COPY ANGKA INI):")
print(urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# Jalankan streamlit secara background
!streamlit run app.py &>/content/logs.txt &

# Buka terowongan localtunnel pada port 8501
!npx localtunnel --port 8501